name: Unit Testing

on:
  push:
    branches:
      - trunk
      - 'release/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test.yml'
      - '**.php'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
  pull_request:
    branches:
      - trunk
      - 'release/**'
    # Only run if PHP-related files changed.
    paths:
      - '.github/workflows/php-test.yml'
      - '**.php'
      - 'phpunit.xml.dist'
      - 'tests/multisite.xml'
      - 'composer.json'
      - 'composer.lock'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  php-test:
    #name: PHP ${{ matrix.php-versions }}
    #runs-on: ubuntu-latest
    #timeout-minutes: 20
    #strategy:
    #  matrix:
    #    php: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0']

    #env:
    #  WP_ENV_PHP_VERSION: ${{ matrix.php }}-fpm
    name: "PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['5.6', '7.4', '8.0']

    env:
      WP_ENV_PHP_VERSION: ${{ matrix.php }}-fpm
      
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v3

      - name: Setup Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
      - name: npm install
        run: npm ci
      - name: Install WordPress
        run: npm run wp-env start
      - name: Running single site unit tests
        run: npm run test-php
      - name: Running multisite unit tests
        run: npm run test-php-multisite
